### PR TITLE
Add TV support

### PR DESCRIPTION
**Pull request by Arudarin**
I am happy to report that I have implemented TV support into netclix!

### CODE REVIEW

**Comment by Arudarin** [comment]
Why is phantom aborting in https://travis-ci.org/ston3o/netclix/jobs/260299753?

**Comment by johackim** [comment]
I fixed phantomjs bug on #13. You can rebase your pull request.

**Comment by Arudarin** [comment]
How do I rebase? Sorry, no access to pc, doing this on mobile.

**Comment by Arudarin** [comment]
See #16.

**Pull request closed without merging**
